name: custom_inspector
description: A customizable inspector that can called directly through Flutter apps.
version: 1.0.1
homepage: https://github.com/fluttercandies/flutter_custom_inspector

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.23.0-19.0.pre.80"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.0.8

flutter:
  uses-material-design: true
