name: custom_inspector
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/fluttercandies/flutter_custom_inspector

environment:
  sdk: ">=2.10.4"
  flutter: ">=1.23.0-19.0.pre.80"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
